environment: &environment
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  facebook:
    app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    secret: <%= ENV["FACEBOOK_SECRET"] %>
    api_version: <%= ENV["FACEBOOK_API_VERSION"] %>
    locale: <%= ENV["FACEBOOK_LOCALE"] %>
  omniauth:
    facebook:
      key: <%= ENV["FACEBOOK_APP_ID"] %>
      secret: <%= ENV["FACEBOOK_SECRET"] %>
    twitter:
      key: <%= ENV["TWITTER_KEY"] %>
      secret: <%= ENV["TWITTER_SECRET"] %>
  socials:
    android: <%= ENV["PORTAL_ANDROID_PAGE"] %>
    facebook: <%= ENV["PORTAL_FACEBOOK_PAGE"] %>
    twitter: <%= ENV["PORTAL_TWITTER_PAGE"] %>
    share_buttons: <%= ENV["SOCIAL_SHARE_BUTTONS_SCRIPT"] %>
  analytics:
    google_tracking_id: <%= ENV["GOOGLE_ANALYTICS_TRACKING_ID"] %>

development: &development
  <<: *environment

test:
  <<: *development
  secret_key_base: 7c495c3cb5886f1b13103c0a816147543ec3d7243d6d02148e8e9969a3650713e7bb3052fad7795e4a6e04990d869d4d0914f703ed797ee54dce54e94e6245c2

production:
  <<: *environment
